name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        id: node-cache
        with:
          path: |
            C:\Users\runneradmin\AppData\Roaming\npm-cache
            node_modules
          key: cd-node14-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cd-node14-${{ runner.os }}-

      - name: Set Up Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload PR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-binaries-${{ github.event.pull_request.number }}
          path: build/
          retention-days: 17